// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBZfQvjKPw0EbOtYcRwyb3qCOSlWxbThj4',
    appId: '1:675590507816:web:f23bb292d2bb462890d41d',
    messagingSenderId: '675590507816',
    projectId: 'trip-planning-70a32',
    authDomain: 'trip-planning-70a32.firebaseapp.com',
    storageBucket: 'trip-planning-70a32.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDbIIoTTTOnduhXOjOPFcd02ZOQvCuB5s4',
    appId: '1:675590507816:android:b48525481dcaefcb90d41d',
    messagingSenderId: '675590507816',
    projectId: 'trip-planning-70a32',
    storageBucket: 'trip-planning-70a32.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAzhmNfGPZUWMDJxTdIYHpZrcAM1oTI1Rc',
    appId: '1:675590507816:ios:c1f33c003464375c90d41d',
    messagingSenderId: '675590507816',
    projectId: 'trip-planning-70a32',
    storageBucket: 'trip-planning-70a32.appspot.com',
    iosBundleId: 'com.example.travelApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAzhmNfGPZUWMDJxTdIYHpZrcAM1oTI1Rc',
    appId: '1:675590507816:ios:c1f33c003464375c90d41d',
    messagingSenderId: '675590507816',
    projectId: 'trip-planning-70a32',
    storageBucket: 'trip-planning-70a32.appspot.com',
    iosBundleId: 'com.example.travelApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBZfQvjKPw0EbOtYcRwyb3qCOSlWxbThj4',
    appId: '1:675590507816:web:c6034c813d5e984a90d41d',
    messagingSenderId: '675590507816',
    projectId: 'trip-planning-70a32',
    authDomain: 'trip-planning-70a32.firebaseapp.com',
    storageBucket: 'trip-planning-70a32.appspot.com',
  );
}